mode: category
# base_path: ./data/MAMS-ACSA
base_path: ./dataset/raw
glove_path: ./word2vec/baomoi.window2.vn.model.txt
sentiment_path: ./data/sentiment_dict.json
lowercase: True
max_vocab_size: None
min_vocab_freq: 0
aspect_category_model:
  type: recurrent_capsnet
  recurrent_capsnet:
    embed_size: 300
    dropout: 0.5
    num_layers: 2
    capsule_size: 300
    bidirectional: True
    optimizer: adam
    batch_size: 64
    learning_rate: 0.001
    weight_decay: 0
    num_epoches: 20
    gpu: 0